# Generated by Django 4.2.3 on 2023-08-09 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FashionWorld', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pimage',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='pname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='pprice',
            new_name='price',
        ),
    ]
