# Generated by Django 4.2.3 on 2023-09-19 07:03

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('FashionWorld', '0002_rename_pimage_product_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomePermissionCheck',
            fields=[
                ('permission_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.permission')),
            ],
            bases=('auth.permission',),
            managers=[
                ('objects', django.contrib.auth.models.PermissionManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'permissions': [('category_check_permission', ' check category permission s valid or not')], 'verbose_name': 'category'},
        ),
    ]
