# Generated by Django 4.2.3 on 2023-08-04 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_name', models.CharField(max_length=25)),
                ('class_name', models.CharField(max_length=25)),
                ('roll_number', models.IntegerField()),
                ('user_age', models.IntegerField()),
                ('user_phone', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Student',
                'db_table': 'Student',
            },
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('student_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='modelinheritence.student')),
                ('month', models.DateField()),
                ('present_days', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('modelinheritence.student',),
        ),
    ]
