# Generated by Django 4.2.3 on 2023-08-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelinheritence', '0002_personproxy_personfullname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonFullName',
        ),
        migrations.CreateModel(
            name='PersonVideoProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('modelinheritence.personproxy',),
        ),
        migrations.AddField(
            model_name='personproxy',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='personproxy',
            name='type',
            field=models.CharField(choices=[('image', 'img'), ('video', 'video')], default='image', max_length=5),
        ),
        migrations.AddField(
            model_name='personproxy',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
