# Generated by Django 4.2.3 on 2023-07-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=80)),
                ('message', models.TextField()),
                ('phone_number', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'ContactUsData',
                'db_table': 'ContactUsData',
            },
        ),
    ]
