# Generated by Django 4.2.3 on 2023-07-31 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactdata',
            options={'permissions': (('a_random_permission', 'it is a random permission'),), 'verbose_name': 'ContactUsData'},
        ),
    ]
