# Generated by Django 4.2.3 on 2023-07-31 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_contactdata_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactdata',
            options={'permissions': [('a_random_permission', 'it is a random permission')], 'verbose_name': 'ContactUsData'},
        ),
    ]
