# Generated by Django 4.2.3 on 2023-07-31 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_contactdata_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('new_permission_add', 'this is just for demo')],
                'managed': False,
            },
        ),
    ]
