# Generated by Django 4.2.3 on 2023-07-31 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_permissionmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissionmodel',
            options={'default_permissions': (), 'managed': False, 'permissions': [('new_permission_add', 'this is just for demo')]},
        ),
    ]
