# Generated by Django 4.2.3 on 2023-09-15 18:58

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_permissionmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdata',
            name='email',
            field=models.EmailField(max_length=80, validators=[home.models.custom_validator]),
        ),
    ]
