# Generated by Django 4.2.3 on 2023-08-08 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinguser',
            name='state',
            field=models.CharField(choices=[('India', 'India'), ('Pakistan', 'Pakistan'), ('Nepal', 'Nepal'), ('Shri Lanka', 'Shri Lanka')], max_length=50),
        ),
    ]
