# Generated by Django 4.2.3 on 2023-08-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_otpgenrator'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpgenrator',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
