# Generated by Django 4.2.3 on 2023-09-08 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_otpgenrator_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppinguser',
            options={'permissions': (('can_add_data', 'can add a new data'),)},
        ),
    ]
