# Generated by Django 4.2.3 on 2023-09-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='images/userImages/profilepic.jpg', upload_to='profile_pics'),
        ),
    ]
