# Generated by Django 4.2.3 on 2023-09-16 04:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinguser',
            name='friends',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
